name: spira
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2024110800

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  # http requests
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.3.1
  # state management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  # service locator
  get_it: ^7.7.0
  # local storage
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  flutter_secure_storage: ^9.2.2
  # find location on the file system
  path_provider: ^2.1.3
  # loading widget
  flutter_easyloading: ^3.0.5
  # permissions
  permission_handler: ^11.3.1
  # sound
  flutter_sound: ^9.5.0
  audio_waveforms: ^1.0.5
  # connectivity
  connectivity_plus: ^6.0.4
  # images
  gif: ^2.3.0
  vector_graphics: ^1.1.11+1
  flutter_svg: ^2.0.10+1
  # toast
  fluttertoast: ^8.2.6
  # auto size text
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner:
  flutter_gen_runner:
  drift_dev:
  bloc_test:
  mocktail:
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/icon.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/.
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
